[2025-01-02T13:37:21.760+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-02T13:37:21.793+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_finance_data_pipeline.pyspark_task manual__2025-01-02T13:37:16.591005+00:00 [queued]>
[2025-01-02T13:37:21.814+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_finance_data_pipeline.pyspark_task manual__2025-01-02T13:37:16.591005+00:00 [queued]>
[2025-01-02T13:37:21.815+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-01-02T13:37:21.848+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): pyspark_task> on 2025-01-02 13:37:16.591005+00:00
[2025-01-02T13:37:21.865+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2147) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-02T13:37:21.868+0000] {standard_task_runner.py:72} INFO - Started process 2155 to run task
[2025-01-02T13:37:21.876+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'gold_finance_data_pipeline', 'pyspark_task', 'manual__2025-01-02T13:37:16.591005+00:00', '--job-id', '306', '--raw', '--subdir', 'DAGS_FOLDER/Gold_finance_etl_dags.py', '--cfg-path', '/tmp/tmpvezjymyo']
[2025-01-02T13:37:21.883+0000] {standard_task_runner.py:105} INFO - Job 306: Subtask pyspark_task
[2025-01-02T13:37:22.210+0000] {task_command.py:467} INFO - Running <TaskInstance: gold_finance_data_pipeline.pyspark_task manual__2025-01-02T13:37:16.591005+00:00 [running]> on host 77bcd09e75b5
[2025-01-02T13:37:22.490+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_finance_data_pipeline' AIRFLOW_CTX_TASK_ID='pyspark_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T13:37:16.591005+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-02T13:37:16.591005+00:00'
[2025-01-02T13:37:22.492+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-02T13:37:29.715+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2025-01-02T13:37:29.718+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-01-02T13:37:29.718+0000] {java_gateway.py:1055} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2025-01-02T13:37:29.720+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-01-02T13:37:29.721+0000] {logging_mixin.py:190} INFO - An error occurred: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext
[2025-01-02T13:37:29.722+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-02T13:37:29.743+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-02T13:37:29.744+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=gold_finance_data_pipeline, task_id=pyspark_task, run_id=manual__2025-01-02T13:37:16.591005+00:00, execution_date=20250102T133716, start_date=20250102T133721, end_date=20250102T133729
[2025-01-02T13:37:29.788+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-02T13:37:29.822+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-02T13:37:29.827+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
